In [2]:
import torch

m = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
print(m.shape)

torch.Size([2, 3])


In [5]:
print(m.ndim)

2


In [6]:
print(m.T)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [7]:
print(m.view(3, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [8]:
import numpy as np

In [9]:
np_arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [10]:
new_t = torch.from_numpy(np_arr)

In [11]:
print(new_t.dtype)

torch.float64


In [12]:
new_t = new_t.to(torch.float32)

In [13]:
print(new_t.dtype)

torch.float32
