In [1]:
import torch

In [2]:
#model parameter
w_1 = torch.tensor([0.23], requires_grad=True)
b = torch.tensor([0.1], requires_grad=True)

# input and target
x_1 = torch.tensor([1.23])
y = torch.tensor([1.])

In [3]:
u = x_1 * w_1
z = u + b
print(z)

tensor([0.3829], grad_fn=<AddBackward0>)


In [4]:
a = torch.sigmoid(z)
print(a)

tensor([0.5946], grad_fn=<SigmoidBackward0>)


In [5]:
import torch.nn.functional as F

# loss function
l = F.binary_cross_entropy(a, y)
print(l)

tensor(0.5199, grad_fn=<BinaryCrossEntropyBackward0>)


In [6]:
from torch.autograd import grad

In [7]:
grad_l_w1 = grad(l, w_1, retain_graph=True)
print(grad_l_w1)

(tensor([-0.4987]),)


In [8]:
grad_l_b = grad(l, b, retain_graph=True)
print(grad_l_b)

(tensor([-0.4054]),)


In [9]:
l.backward() # auto gradient decent

In [10]:
w_1.grad

tensor([-0.4987])

In [11]:
b.grad

tensor([-0.4054])