In [2]:
import torch
# template for model training
class MyClassifier(torch.nn.Module):
    def __init__(self):
        # define model parameters
        pass

    def forward(self, x):
        # define how model
        # produces outputs
        pass

In [3]:
# using predefined NN layer
import torch
torch.manual_seed(123)

linear = torch.nn.Linear(in_features = 2, out_features = 1)

In [4]:
print(linear.weight)

Parameter containing:
tensor([[-0.2883,  0.0234]], requires_grad=True)


In [5]:
print(linear.bias)

Parameter containing:
tensor([-0.3512], requires_grad=True)


In [6]:
w = linear.weight.detach()
b = linear.bias.detach()
x = torch.tensor([[1.2, 0.5]])
z = x.matmul(w.T) + b

# same as z = linear(x)
print(z)

tensor([[-0.6855]])


In [8]:
# handle mini batches
x = torch.tensor([[1.2, 0.5],
                  [0.7, 0.8],
                  [0.1, 1.2]])
z = x.matmul(w.T) + b
print(z)

# same as z = linear(x)

tensor([[-0.6855],
        [-0.5343],
        [-0.3519]])
